Microsoft/dotnet-reliability

src/triage.python/analysis_worker.py, src/triage.python/analysis_worker_config.json, src/triage.python/analysis_worker_monitor.sh, src/triage.python/dumpling_util.py, src/triage.python/nearby_config.py, src/triage.python/triage.python.pyproj
Messed this up because I was missing my changes to pyproj.
=> moving worker in to triage.python

src/triage.python/analysis_worker.py, src/triage.python/dumpling_util.py, src/triage.python/nearby_config.py
- NearbyConfig no longer depends on Logging class.
- Added 'Event' method to Logging class. (parameter is of a 'kind')
- Added business profiling events to code
=> adding eventhub support to analyzers

src/stress.codegen/ExecutionFileGenerator.cs, src/triage.python/triage.ini
updating core dump filter settings in stress.sh
updating triage.ini to add heap verify frames to heap_corruption
=> minor updates

src/triage.python/analysis.py
Fixes frame parsing issue described in issue [#49](https://github.com/Microsoft/dotnet-relibility/issues/49)
=> Fixing frame parsing issue 

src/triage.python/analysis.py, src/triage.python/triage.ini
update to analysis.py to ignore frames with missing method or module symbols
update triage.ini to ignore more EH frames
=> bucketing updates

src/dirs.proj, src/dumpling-service/dumpling-service.sln, src/dumpling-service/dumpling.dataworker/Properties/AssemblyInfo.cs, src/dumpling-service/dumpling.deploy/Program.cs, src/dumpling-service/dumpling.library/DumplingDataWorkerQueueController.cs, src/dumpling-service/dumpling/App.config, src/dumpling-service/dumpling/HelixCommand.cs, src/dumpling-service/dumpling/Program.cs, src/dumpling-service/dumpling/Properties/AssemblyInfo.cs, src/dumpling-service/dumpling/RootCommand.cs, src/dumpling-service/dumpling/dumpling.csproj, src/dumpling-service/dumpling/helix/HelixResultsStorage.cs, src/dumpling-service/dumpling/packages.config
Removed the secrets. You know where to find them...I hope.
=> adding dumpling client

src/dirs.proj, src/stress.codegen/ProjectJsonDependencyInfo.cs, src/triage.database/TriageDb.cs
-removing dumpling.csproj from src/dirs.proj
-removing static ctor from Traige.db
-changing debian.8.1-x64 runtime id to debian.8-x64 due to corefx change  #9004
=> minor fixes to test build

src/triage.python/analysis_worker.py, src/triage.python/analysis_worker_monitor.sh, src/triage.python/dumpling_util.py, src/triage.python/dumplingstatetable.py
- Fixing SOS Issues
- Fixing deadlock that resulted from new approach to work around SOS
issues.
- Other minor fixes
=> Triage changes

src/stress.codegen/ExecutionFileGenerator.cs, src/stress.codegen/HelixToFProjectFileGenerator.cs, src/stress.codegen/LoadTestProjectFileGenerator.cs, src/stress.codegen/LoadTestProjectJsonFileGenerator.cs, src/stress.codegen/LoadTestSourceFileGenerator.cs, src/stress.codegen/ProgramSourceFileGenerator.cs, src/stress.codegen/SourceFileInfo.cs, src/stress.codegen/ToFProjectFileGenerator.cs, src/stress.codegen/UnitTestInfo.cs, src/stress.codegen/XUnitTestDiscoverer.cs, src/triage.python/dumpling.py
-updated script generation to upload dumps directly to dumpling service
-fixed issue with async tests not being throttled propertly
-fixed issue with dumpling upload for users with mixed case usernames
=> updates to autoupload dumps from stress runs with dumpling.py

src/stress.codegen/ExecutionFileGenerator.cs
-updated core file existence check to use regex instead of looking for only 'core'
-removed non-working sudo solution to set core_pattern
=> fix for generated execution file dumpling collection

src/dumpling-service/dumpling.azure/ServiceDefinition.csdef, src/dumpling-service/dumpling.deploy/Program.cs, src/dumpling-service/dumpling.web/App_Start/RouteConfig.cs, src/dumpling-service/dumpling.web/Controllers/DumplingServiceController.cs, src/dumpling-service/dumpling.web/Controllers/HomeController.cs, src/dumpling-service/dumpling.web/Views/Home/Index.cshtml, src/dumpling-service/dumpling/RootCommand.cs
- Restrict ranges query 
- Minor fixes
- Redhat messages are delivered through the centos subscription.
Note:
- Already published the site.
=> Restrict ranges feature request

toolbox/list_build_ids/DumpCore.sln, toolbox/list_build_ids/DumpCore.vcxproj, toolbox/list_build_ids/list_build_ids.cpp
Added a tool to list modules within a core dump and their associated build id.
=> Added tool to list build id of modules in a core dump

src/triage.python/dumpling.py
-updated upload command to call dumpling service method UpdateTriageInfo
-added update command to upload additional triage data
=> updates to dumpling.py client triage data services

src/triage.python/dumpling.py
During automated CI runs it's simpler for us to retrieve data coming from stdout. In order to facilitate this, I'm adding a squelch feature to dumpling so that it outputs essential/expected information by the CI runs.
=> Adding squelch to dumpling.py

src/triage.python/dumpling.py
Narrow feature, but I need to be able to amend essential dumpling information to a pre-existing log file. This is that.
=> adding ability to capture essential output to an existing log

src/triage.python/dumpling.py
I mistakenly did the work in the wrong repo and pushed the work to this branch. Merging it with master.
=> Dumpling ci work

toolbox/list_build_ids/DumpCore.vcxproj, toolbox/list_build_ids/example.py, toolbox/list_build_ids/list_build_ids.cpp, toolbox/list_build_ids/python_binding.cpp, toolbox/list_build_ids/setup.py
Added an example of using a native python module to enumerate build ids.
=> Add example of getting build ids in python

src/stress.codegen/ExecutionFileGenerator.cs, src/stress.codegen/resources/runstress.sh, src/stress.codegen/stress.codegen.csproj, src/stress.execution/StressTestShim.cs
-adding STRESS_TESTID and STRESS_BUILDID to the test environment for dumpling properties
-fixes for runstress.sh
-fixed missing stress.codegen.csproj updates including reasources folder
-updated StressTestShim to output console data to the exception message for easier reporting in helix
=> execution flow updates

src/stress.codegen/ExecutionFileGenerator.cs, src/stress.codegen/ProgramSourceFileGenerator.cs, src/stress.codegen/resources/runstress.sh, src/stress.execution/SelfDestruct.cs, src/stress.execution/stress.execution.csproj
=> Updates to stress execution

src/stress.codegen/ExecutionFileGenerator.cs, test/genstress.proj
-fix for stress execution script generation to fix duplicate environment setup issue
-update genstress.proj to use OfficialBuildId as a SuiteName if it is set
=> stress.codegen updates / minor bug fixes

src/stress/StressEssentials.ps1
-making branch configurable to enable pulling the product / tests from multiple branches with master as the default
=> updating StressEssentials.ps1 product aquisition
